apiVersion: v1
kind: Secret
metadata:
  name: telegram-secret
type: Opaque
stringData:
  token: "7995348421:AAHyB-1c0B3WzX0E__IhgL4cHjAmr511bgs"

---
apiVersion: v1
kind: Secret
metadata:
  name: minio-secret
type: Opaque
stringData:
  access_key: "minio"
  secret_key: "minio123"
