FROM python:3.11-slim

RUN apt-get update && apt-get install -y \
    gcc \
    libssl-dev \
    netcat-openbsd \
    && rm -rf /var/lib/apt/lists/*

# Сначала копируем только requirements.txt
COPY requirements.txt /tmp/
RUN pip install --no-cache-dir -r /tmp/requirements.txt
